# Generated by Django 5.2.9 on 2025-12-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseInfoDetails',
            fields=[
                ('CaseInfoDetailsId', models.AutoField(primary_key=True, serialize=False)),
                ('stateId', models.IntegerField()),
                ('districtId', models.IntegerField()),
                ('unitId', models.IntegerField()),
                ('Office', models.TextField(blank=True, max_length=255, null=True)),
                ('letterNo', models.CharField(blank=True, max_length=100, null=True)),
                ('caseDate', models.DateTimeField(blank=True, null=True)),
                ('caseType', models.CharField(default=True, max_length=100, null=True)),
                ('caseNo', models.CharField(max_length=17, unique=True)),
                ('firNo', models.CharField(max_length=255)),
                ('author', models.TextField(blank=True, max_length=200, null=True)),
                ('toAddr', models.TextField(blank=True, max_length=500, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('caseStatus', models.IntegerField(blank=True, null=True)),
                ('lastmodified_Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('finalReportCaseStatus', models.IntegerField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'permissions': [('view_searchcaseFiles', 'can search the case and file details'), ('add_filepreviewapi', 'can preview a file')],
            },
        ),
        migrations.CreateModel(
            name='CaseTransfer',
            fields=[
                ('caseTransferId', models.AutoField(primary_key=True, serialize=False)),
                ('fromDeptId', models.IntegerField()),
                ('fromdivisionId', models.IntegerField()),
                ('toDeptId', models.IntegerField()),
                ('todivisionId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('revoked', 'Revoked'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('revoke_startdate', models.DateField(blank=True, null=True)),
                ('revoke_enddate', models.DateField(blank=True, null=True)),
                ('is_revoked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FileDetails',
            fields=[
                ('fileId', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=255)),
                ('filePath', models.TextField()),
                ('fileHash', models.CharField(max_length=64)),
                ('hashTag', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('isArchieved', models.BooleanField(default=False)),
                ('caseType', models.CharField(default=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileUploadApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('revoked', 'Revoked'), ('denied', 'Denied')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.IntegerField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('UPLOAD_APPROVAL', 'Upload Approval'), ('ACCESS_REQUEST', 'Access Request'), ('GENERIC', 'Generic')], default='GENERIC', max_length=30)),
                ('department', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
