"""
Django settings for RRMSAPI project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import datetime, timedelta
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_29_+m4pu4x66=2l8milapzgrt2159te599c)ywhj#i*ca@(j2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTSsettings = ALLOWED_HOSTS = [os.getenv("RENDER_EXTERNAL_HOSTNAME", "localhost")]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'corsheaders',
    'mdm',
    'users',
    'caseInfoFiles.apps.CaseinfofilesConfig',
    'ManageContent.apps.ManagecontentConfig'
]

# MEDIA_URL = '/uploads/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'RRMSAPI.core.middleware.DRFLoggingMiddleware'
]

X_FRAME_OPTIONS = 'ALLOWALL'

ROOT_URLCONF = 'RRMSAPI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'RRMSAPI.wsgi.application'



# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# 'default': {
    #    'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': config('DB_NAME'),
    #     'USER': config('DB_USER'),
    #     'PASSWORD': config('DB_PASSWORD'),
    #     'HOST': config('DB_HOST'),
    #     'PORT': config('DB_PORT'),
    # }
      # 'USER': 'your_user',
        # 'PASSWORD': 'your_password',
        # 'PORT': '1433',
        # 'default': {
        # 'ENGINE': 'mssql',
        # 'NAME': 'RRMS',
        # 'HOST': 'BUDHA\\MSSQLSERVER03',
        # 'OPTIONS': {
        #     'driver': 'ODBC Driver 17 for SQL Server',
        #     'trusted_connection': 'yes',
        #     'extra_params': 'Encrypt=yes;TrustServerCertificate=yes;'

        # },
        
DATABASES = {
          'default': {
        'ENGINE': 'mssql',
        'NAME': 'RRMSDb',
        'HOST': 'BUDHA\\MSSQLSERVER03',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'trusted_connection': 'yes',
            'extra_params': 'Encrypt=yes;TrustServerCertificate=yes;'

        },
          }
}


STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    'http://localhost:4200',
    'https://rrms-frontend.vercel.app'
]

CORS_ALLOW_HEADERS = [
     'accept',
    'accept-encoding',
    'authorization',
    'cache-control',  # Add 'cache-control' to the allowed headers
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_CREDENTIALS = True

AUTH_USER_MODEL = "users.User"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'URL_TRAILING_SLASH': False,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}


SIMPLE_JWT = {
    'ALGORITHM': 'HS256',  # Default algorithm for signing JWT tokens
    'SIGNING_KEY': 'SECRET@123',  # You can use Django's SECRET_KEY here
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
}

USE_TZ = True
TIME_ZONE = 'UTC'

EMAIL_BACKEND = config('EMAIL_BACKEND')
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_USE_TLS = config('EMAIL_USE_TLS')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD =  config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')

LOGGING_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGGING_DIR):
    os.makedirs(LOGGING_DIR)

today_date = datetime.now().strftime("%Y-%m-%d")
log_filename = os.path.join(LOGGING_DIR, f"drf_{today_date}.log")

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '[{asctime}] [{levelname}] {name} - {message}',
            'style': '{',
        },
    },

    'handlers': {
        'daily_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': log_filename,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
     'loggers': {
        'django.request': {
            'handlers': ['daily_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'drf_logger': {
            'handlers': ['daily_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}